-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 16:18:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reddit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reddit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reddit` DEFAULT CHARACTER SET utf8 ;
USE `reddit` ;

-- -----------------------------------------------------
-- Table `reddit`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reddit`.`subreddits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`subreddits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reddit`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`subscriptions` (
  `user_id` INT NOT NULL,
  `subreddit_id` INT NOT NULL,
  `moderator` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `subreddit_id`),
  INDEX `fk_users_has_subreddits_subreddits1_idx` (`subreddit_id` ASC),
  INDEX `fk_users_has_subreddits_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_subreddits_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `reddit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_subreddits_subreddits1`
    FOREIGN KEY (`subreddit_id`)
    REFERENCES `reddit`.`subreddits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reddit`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `subreddit_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users1_idx` (`user_id` ASC),
  INDEX `fk_posts_subreddits1_idx` (`subreddit_id` ASC),
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reddit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_subreddits1`
    FOREIGN KEY (`subreddit_id`)
    REFERENCES `reddit`.`subreddits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reddit`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`comments` (
  `id` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  INDEX `fk_comments_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reddit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `reddit`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reddit`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `recipient_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_users1_idx` (`recipient_id` ASC),
  INDEX `fk_messages_users2_idx` (`author_id` ASC),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `reddit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users2`
    FOREIGN KEY (`author_id`)
    REFERENCES `reddit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reddit`.`comment_votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`comment_votes` (
  `user_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  `type` TINYINT NULL,
  PRIMARY KEY (`user_id`, `comment_id`),
  INDEX `fk_users_has_comments_comments1_idx` (`comment_id` ASC),
  INDEX `fk_users_has_comments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reddit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_comments_comments1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `reddit`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reddit`.`post_votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reddit`.`post_votes` (
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `type` TINYINT NULL,
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `fk_posts_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_posts_has_users_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_posts_has_users_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `reddit`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reddit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
